@startuml

skinparam classAttributeIconSize 0
hide circle
skinparam monochrome true

skinparam class {
	BackgroundColor transparent
}

skinparam node {
	BackgroundColor transparent
}

skinparam Header {
	FontColor black
}

skinparam Footer {
	FontColor black
}

title 武漢肺炎的感染鏈關係圖(香港) 2020-02-23\n\n

cloud "深圳" as ShenZhen

cloud "珠海" as Zhuhai

cloud "北京樓" as PekingRest

cloud "青衣" as TsingYi {

  database "康美樓" as HongMei {
    card 42
    card 12
		card 49
		card 48
    42 --- 12: 樓上樓下鄰居
  }
  card 21
  card 22
  card 50
  22-->21: 妻子
}

cloud "西灣河" as SaiWanHo {
  card 38
  card 40
  card 39
	card 23
  39 --> 38: 太太
  40 --> 38: 外母
}

cloud "小西灣" {
	card 64 <<已減少出門>>
	card 65 <<已減少出門>>
}

package "警察" as Police {
	actor 69
}

card 41
cloud "打邊爐家族" as HotPotFamily {

	cloud "住灣仔" as HotPotFamilyWanChain {
		card 27
		card 29
		card 30
		card 31
		card 33
		card 36
	}

  card 37
  card 32
  card 34
  card 35
  29 --> 27: 外婆
  30 --> 27: 父親
  31 --> 27: 母親
  32 --> 27: 表弟
  33 --> 27: 四姨
  34 --> 27: 表姐
  35 --> 27: 三姨
  36 --> 27: 表弟
  37 --> 27: 阿姨
  41 --> 35: 丈夫
}

card 40
card 51
card 39

cloud "無外遊記錄&&可追蹤源頭&&未分類" as NoRecord {
  card 16
  card 17
  card 18
  card 24
  card 28
  card 43
	card 45
  card 47
	card 56
  card 58
	card 67
	card 68
	card 70
	card 72
	card 73
	card 74
}

cloud "澳門" as Macau

cloud "武漢" as Wuhan {
  card 1
  card 3
  card 4
  card 5
  card 8

  cloud "在港住W酒店" as WHotel {
    card 9
    card 10
  }

  5--> 4: 丈夫
  8--> 3: 丈夫
}

cloud "太古城" as TaikooShing {
	card 46
	card 57
	card 60
}

cloud "灣仔" as WanChai {
	card 53
}

cloud "鑽石公主號" as DiamondPrincess

cloud "醫管局" as HA
cloud "河北"
cloud "東莞"

card 59
card 14
card 39
card 11
card 2
card 6
card 7
card 44
card 52
card 61
card 13 <<死亡>>
card 15
card 19
card 20
card 25
card 26
card 54
card 55 <<死亡>>
card 62
card 63 <<無病徵確診>>
card 66
card 71

49 --> 42: 兒子
46 --> 48: 父親
21 --> ShenZhen
20 --> 17: 妻子
19 --> 17: 女兒
15 -> 13: 父親
14 --- DiamondPrincess
11 --> 10: 女兒
11 --> 9: 女兒
2 --> Wuhan
6 --> Wuhan
7 --> Wuhan
13 --> Wuhan
44 -- 30: 同事
52 --> 61: 僱主
52 --> 46: 小姨
48 --> 42: 媳婦
42 --> Macau
12 --> Macau
25 --> Macau
25 --> Zhuhai
26 --> Macau
26 --> Zhuhai
26 --> 河北
50 --> 37: 同事
51 --> 47: 親戚
53 -> 52: 兒子
54 -> 53: 表姐
55 --> ShenZhen
59 -- HA
57 -- HA
60 --> 57: 妻子
14 --> ShenZhen
50 --- PekingRest
37 -- PekingRest
36 -- PekingRest
16 -- SaiWanHo
62 --> Macau
63 -> 60: 母親
63-> 57: 岳母
59 -- 57: 同事
65 -- 64: 妻子
66 -> 63: 丈夫
66 --> 東莞: 多次前往
71 --> DiamondPrincess
HotPotFamilyWanChain -- WanChai

/'Layout
HotPotFamily -[hidden]---- NoRecord
SaiWanHo -[hidden] 小西灣
'/

TsingYi -[hidden]------ Wuhan
TsingYi -[hidden]----- NoRecord
NoRecord -[hidden]- SaiWanHo
NoRecord -[hidden]- 小西灣

left footer
資料來源：
https://wars.vote4.hk/cases
endfooter

@enduml
